config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'notes#index'

  resources :notes
  resources :users, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :note

end

app/models/note.rb
class Note < ApplicationRecord

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :likers, class_name: 'User', through: :likes

  validates :title, presence: true
  validates :body, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]


  has_many :notes, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followees, through: :active_relationships

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followee_id, dependent: :destroy
  has_many :followers, through: :passive_relationships

  has_many :likes, dependent: :destroy
  has_many :liked, class_name: 'Note', through: :likes, source: :note


  def follow(user)
    followees << user unless self.following?(user) || self == user
  end

  def following?(user)
    followees.include?(user)
  end

  def unfollow(user)
    followees.delete(user)
  end

  def like(note)
    liked << note unless self.liked?(note)
  end

  def liked?(note)
    liked.include?(note)
  end

  def unlike(note)
    liked.delete(note)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @note = Note.find(params[:format])
    if current_user.like(@note)
      flash[:notice] = "You have liked the note!"
      # byebug
      UserMailer.notification(@note.user).deliver_later
      redirect_to notes_path
    end
  end

  def destroy
    @note = Note.find(params[:id])
    if current_user.unlike(@note)
      flash[:notice] = "You have unliked the note!"
      UserMailer.unlikenotification(@note.user).deliver_later
      redirect_to notes_path
    end
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

before_action :authenticate_user!, only: [:create, :destroy, :edit, :update]

  def index
    if user_signed_in?
      @users = current_user.followees
      @note_users = [current_user] + @users
      @notes = Note.where(user_id: @note_users).reverse
    else
      @users = User.all
      @notes = Note.all.reverse
    end
    @note = Note.new
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      flash[:notice] = "Note saved!"
      redirect_to notes_path
    else
      if user_signed_in?
        @users = current_user.followees
        @note_users = [current_user] + @users
        @notes = Note.where(user_id: @note_users)
      else
        @users = User.all
        @notes = Note.all.reverse
      end
      @note = Note.new
      flash.now[:alert] = "Oops! Note not saved!"
      render :index
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    flash[:alert] = "Note deleted!"
    redirect_to notes_path
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      flash[:notice] = "Note updated!"
      redirect_to notes_path
    else
      flash.now[:alert] = "Oops, note did not update!"
      render :edit
    end
  end

  private

    def note_params
      params.require(:note).permit(:title, :body)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:format])
    if current_user.follow(@user)
      flash[:notice] = "You are now following " + @user.email
      redirect_to users_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    current_user.unfollow(@user)
    flash[:alert] = "You are no longer following " + @user.email
    redirect_to users_path
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
html
  head
    title MyAcFinalAssessment
    = csrf_meta_tags
    link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    - flash.each do |name, msg|
       .card = content_tag :div, msg, class: name
    nav.navbar-dark.bg-dark.p-3.fixed-top
      .container
        = link_to 'Home', notes_path, class: 'navbar-brand btn'
        = link_to 'Users', users_path, class: 'navbar-brand btn'
        - if user_signed_in?
          .navbar-brand.btn.border = 'Welcome, ' + current_user.email.split('@')[0].capitalize + '!'
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-brand btn'
        - else
          = link_to 'Login', new_user_session_path, class: 'navbar-brand btn'
          = link_to 'Sign Up', new_user_registration_path, class: 'navbar-brand btn'

    = yield

app/views/notes/_new.html.slim
= simple_form_for @note do |f|
  = f.input :title
  = f.input :body
  = f.button :submit

app/views/notes/edit.html.slim
h1.jumbotron Edit Note | Kenneth's Note App

.container.p-4.card
  = simple_form_for @note do |f|
    = f.input :title
    = f.input :body
    = f.button :submit

  = link_to 'Back to home', notes_path

app/views/notes/index.html.slim
h1.jumbotron.bg-warning Welcome to Kenneth's Notes App!

.container
  - if user_signed_in?
    .row
      .col-10.card.p-4.m-4
        h2 Add a note!
        = render partial: 'new'

  .row
    .col-5.card.p-4.m-3
      .card-header
        - if user_signed_in?
          h2 Followed Users
        - else
          h2 Users
      .card-body
        - @users.each do |user|
          p = user.email
          hr
    .col-5.card.p-4.m-3
      .card-header
        h2 Notes
      .card-body
        - @notes.each do |note|
          h5 = note.title
          p = note.body
          p = 'by ' + note.user.email
          p = 'Liked by: ' + note.likes.count.to_s
          p.small = time_ago_in_words(note.created_at) + ' ago'
          - if user_signed_in?
            - unless current_user.liked?(note)
              = link_to 'Like', likes_path(note), method: :create, class: 'btn'
            - if current_user.liked?(note)
              = link_to 'Unlike', like_path(note), method: :delete, class: 'btn'
            - if current_user == note.user
              = link_to 'Edit', edit_note_path(note), class: 'btn'
              = link_to 'Delete', note_path(note), method: :delete, class: 'btn'
          hr

app/views/users/index.html.slim
h1.jumbotron.bg-warning Users | Kenneth's Notes App!

.container
  .row
    .col-10.card.p-4.m-3
      h2 Users
      - @users.each do |user|
        h5 = user.email
        - if !user.notes.empty?
          p = 'Last Note: ' + user.notes.last.title + ' - ' + user.notes.last.body
        - else
          p This user hasn't posted anything!
        - unless current_user.following?(user) || current_user == user
          = link_to 'Follow', relationships_path(user), method: :create, class: 'btn btn-outline-primary'
        - if current_user.following?(user)
          = link_to 'Unfollow', relationship_path(user), method: :delete, class: 'btn btn-outline-danger'
        hr